module DungFs.Data

let rooms = [
  "Aerary"
  "Air shower"
  "Aircraft cabin"
  "Airport lounge"
  "Aisle"
  "Almonry"
  "Andron"
  "Anechoic chamber"
  "Antechamber"
  "Apodyterium"
  "Arizona room"
  "Assembly hall"
  "Atrium"
  "Attic"
  "Auditorium"
  "Aula regia"
  "Ballroom"
  "Bang"
  "Banishment room"
  "Basement"
  "Bathroom"
  "Bedroom"
  "Billiard room"
  "Bonus room"
  "Boudoir"
  "Breezeway"
  "Buttery"
  "Cabin"
  "Cabinet"
  "Cafeteria"
  "Caldarium"
  "Calefactory"
  "Castle chapel"
  "Central apparatus room"
  "Changing room"
  "Church hall"
  "Church porch"
  "Classroom"
  "Cleanroom"
  "Cloakroom"
  "Closet"
  "Committee room"
  "Common room"
  "Companionway"
  "Computer lab"
  "Conference hall"
  "Control room"
  "Conversation pit"
  "Corner office"
  "Count room"
  "Counting house"
  "Courtroom"
  "Cry room"
  "Cryptoporticus"
  "Cubiculum"
  "Cyzicene hall"
  "Darbazi"
  "Darkroom"
  "Den"
  "Dining room"
  "Drawing room"
  "Dungeon"
  "Electrical room"
  "Entryway"
  "Equatorial room"
  "Equipment room"
  "Fainting room"
  "Fallout shelter"
  "Family room"
  "First aid room"
  "Frigidarium"
  "Function hall"
  "Furnace room"
  "Garage"
  "Garden office"
  "Garret"
  "Genkan"
  "Ghorfa"
  "Great chamber"
  "Great hall"
  "Great room"
  "Green room"
  "Hall"
  "Home cinema"
  "Home office"
  "Inglenook"
  "Kitchen"
  "Laconicum"
  "Lactation room"
  "Larder"
  "Laundry room"
  "Living room"
  "Lobby"
  "Locker room"
  "Loft"
  "Long gallery"
  "Lumber room"
  "Luxury box"
  "Maashaus"
  "Mail services center"
  "Mailroom"
  "Majlis"
  "Man cave"
  "Master control"
  "Mechanical floor"
  "Mechanical room"
  "Megaron"
  "Mehmaan khana"
  "Mission control center"
  "Mizuya"
  "Monastic cell"
  "Music rehearsal space"
  "Network operations center"
  "Nilavara"
  "Room number"
  "Nursery"
  "Office"
  "Opisthodomos"
  "Orphanage"
  "Padded cell"
  "Pantry"
  "Parlour"
  "Pinacotheca"
  "Porters' lodge"
  "Presidential suite"
  "Priest hole"
  "Print room"
  "Prison cell"
  "Psychomanteum"
  "Public toilet"
  "Qa'a"
  "Queue area"
  "Rain porch"
  "Recreation room"
  "Refectory"
  "Refreshment room"
  "Reredorter"
  "Riding hall"
  "Roomsharing"
  "Root cellar"
  "Rotting room"
  "Rotunda"
  "Sacristy"
  "Safe room"
  "Sauna"
  "Screened porch"
  "Secret passage"
  "Semi-basement"
  "Sensitive Compartmented Information Facility"
  "Servants' hall"
  "Servants' quarters"
  "Server room"
  "Shoin"
  "Showroom"
  "Sky lobby"
  "Skyway"
  "Sleeping porch"
  "Slype"
  "Small office"
  "Smoking room"
  "Solar room"
  "Spear closet"
  "Staffroom"
  "Staircase tower"
  "State room"
  "Still room"
  "Storm cellar"
  "Student lounge"
  "Studio"
  "Study"
  "Subbasement"
  "Sudatorium"
  "Suite"
  "Sunroom"
  "Tabagie"
  "Tablinum"
  "Tearoom"
  "Tepidarium"
  "Throne room"
  "Toolroom"
  "Transmission control room"
  "Triclinium"
  "Undercroft"
  "Utility room"
  "Utility vault"
  "Vestibule"
  "Vestry"
  "Waiting room"
  "Washitsu"
  "Whispering gallery"
  "Wine cellar"
  "Wiring closet"
  "Workshop"
]

let people = [
  fun () -> {Person.name = "Elf"; health = 20; gold = 2}
  fun () -> {Person.name = "Gremlin"; health = 30; gold = 8}
  fun () -> {Person.name = "Bob"; health = 3; gold = 0}
  fun () -> {Person.name = "Harpy"; health = 18; gold = 1}
  fun () -> {Person.name = "Wolf"; health = 17; gold = 2}
  fun () -> {Person.name = "Giant"; health = 16; gold = 3}
  fun () -> {Person.name = "Snake"; health = 15; gold = 4}
  fun () -> {Person.name = "Cyclops"; health = 14; gold = 5}
  fun () -> {Person.name = "Giant Spider"; health = 13; gold = 6}
  fun () -> {Person.name = "Scorpion Bear"; health = 12; gold = 7}
  fun () -> {Person.name = "Mother in Law"; health = 11; gold = 8}
  fun () -> {Person.name = "Vampire Bunny"; health = 10; gold = 9}
  fun () -> {Person.name = "Boggart"; health = 9; gold = 10}
  fun () -> {Person.name = "Raider"; health = 8; gold = 11}
  fun () -> {Person.name = "Thief"; health = 7; gold = 12}
  fun () -> {Person.name = "Scavenger"; health = 6; gold = 13}
  fun () -> {Person.name = "Bloodthirsty Sheep"; health = 5; gold = 14}
  fun () -> {Person.name = "Angry Kitten"; health = 4; gold = 15}
  fun () -> {Person.name = "Squirrel"; health = 3; gold = 16}
]